[package]
name = "rust-actix-sample"
version = "0.1.0"
authors = ["shouji <shouji.takumi@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "3.3.*"
serde = "1.0.*"
serde_derive = "1.0.*"
r2d2_redis = "0.14.*"
