version: '3.7'

services:
  db:
    image: mysql:5.7
    platform: linux/x86_64
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 8888:3306
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: user 
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev